### ISSUE TITLE
[staging] Winetricks fails upon reinstalling: "wine cmd.exe /c echo '%ProgramFiles%' returned empty string"

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#109]
Currently occurs with wine-staging, untested under wine. Upon selecting the "Reinstall Roblox" option, winetricks seems to always fail with the error presented below:
```
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string
------------------------------------------------------
```

**Comment by GLolol** [comment]
Can't reproduce on Wine 1.7.41.

**Comment by alfonsojon** [comment]
@GLolol I cannot reproduce this in stock wine. It seems to only occur on prefixes that have switched wine versions (i.e. wine to wine-staging). Is it possible that a wineserver is still running in the background?

**Comment by 5shane1** [comment]
I actually used to get that message a lot before.

**Comment by GLolol** [comment]
Update: The winetricks script available at http://winetricks.org/winetricks is way older than what's available in the latest git repository: https://github.com/Winetricks/winetricks. Not to mention that we prefer winetricks packages in official system repositories, which may be even older. As far as I'm concerned, the `%ProgramFiles%` handling has been changed to be more verbose.

My suggestion:

1) Turn RLW into an organization, fork winetricks and import that as a submodule in this repository.
2) Ignore system winetricks and use our submodule only, for consistency/stability purposes.

**Comment by alfonsojon** [comment]
@GLolol I like option #2. #1 seems a bit complex for the scope of this project.

**Comment by GLolol** [comment]
The two options are sort of interconnected... Using an upstream repository as a submodule is okay, but any changes like repository renames might break things. Either way it requires manually syncing up when needed.

**Comment by alfonsojon** [comment]
@GLolol What all will be different by converting to an organization?

**Comment by GLolol** [comment]
I'll fix it later today.

**Comment by alfonsojon** [comment]
@GLolol Thanks.

**Comment by GLolol** [comment]
Well, it wouldn't change much as far as the code goes, but management would look a bit different. A normal repo only has one owner and any number of collaborators, while a group has more access levels: owner, admin, collaborator, viewers. A group also allows multiple repositories to be added, and assigning teams to different repositories.

**Comment by GLolol** [comment]
Possibly related: Winetricks/winetricks#163.

**Comment by alfonsojon** [comment]
@GLolol To convert roblox-linux-wrapper to an organization would require my account to also be an organization, which is something I'm not looking to do. Neat features though, I'll keep that in mind for any future projects :)

**Comment by GLolol** [comment]
No it doesn't. You can create an organization and then transfer this repository to it in the settings.

**Comment by alfonsojon** [comment]
@GLolol Would the organization still be managed by my account, or is it a separate entity entirely?

**Comment by GLolol** [comment]
You will have full owner access if you create it. There will be a button in the homepage that allows you to switch the dashboard context to the organization.

**Comment by alfonsojon** [comment]
@GLolol Figured it out, thanks!

**Comment by GLolol** [comment]
I'm going to push some things to testing that makes us use our own winetricks copy. Note that I can't test with wine-staging without compiling myself (libraries on my system are too new, figures), but Wine 1.7.43 should be newer than Wine 1.7.42 staging AFAIK.

**Comment by GLolol** [comment]
Update: can't reproduce on Wine 1.7.43. My guess is that the issue is sporadic, like a lot of the other bugs we deal with.

**Comment by alfonsojon** [comment]
I cannot reproduce this under wine 1.7.43 as well. It seems to only be affecting wine-staging currently.

**Comment by GLolol** [comment]
I forget: can you test on the latest RLW master? It uses the Git master of winetricks.

**Comment by alfonsojon** [comment]
Sure thing

**Comment by GLolol** [comment]
bump

**Comment by alfonsojon** [comment]
I have not tested (go me!), thanks for the bump.

**Comment by alfonsojon** [comment]
Can no longer reproduce, closed.
