### ISSUE TITLE
wineserver --wait not working with wine-staging, implement workaround

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#110]
For some reason, wineserver --wait is not working with wine-staging. A workaround should be applied in order to fix this.

**Comment by GLolol** [comment]
Can this be reproduced with Wine staging 1.7.44?

**Comment by GLolol** [comment]
Marking as fixed since I can no longer reproduce on staging 1.7.44.
