### ISSUE TITLE
[META ISSUE] ROBLOX crashing [POST CRASHES HERE]

### ISSUE THREAD

**Issue by GLolol** [roblox-linux-wrapper/roblox-linux-wrapper#115]
Lately, we've received numerous issues regarding ROBLOX crashing under Wine: #96, #107, #114, #111, #104, #102, #99, #97, #90, #64. This is an attempt to unify all these separate issues with the appropriate information needed. **Often times, ROBLOX crashes are Wine bugs that we have _no control over_ - we can only _attempt_ workarounds, but those may or may not work**. 

Please keep this thread concise and to the point. **I know this is a frustrating issue, but comments like "help game is not working!!!11!" with no further information DO NOT help solve any issues.**

**To file a report, please include the following:**
- Roblox Linux Wrapper version
- Wine version
- OS Distro name + version
- CPU architecture (32 or 64-bit)
- Graphics card model + driver used

Crash logs should go in a pastebin for easier reading.

**Comment by 5shane1** [comment]
Eh, still crashs for me... But we all know it's a wine bug, but I guess everyone are newbies at linux... :L

**Comment by skullbro** [comment]
yep :D

**Comment by josephskimber** [comment]
sry i was away since my last post on the other one. im going to go over everything again and double check all my installs and see if its still a problem. brb

**Comment by josephskimber** [comment]
ok so mint updated and now its back to "wine closed unsuccesfully" i unstalled everything and started from the begining. i now get this, its at the end when installing the wrapper....

finnegan@finnegan-NV53A ~ $ echo 'deb http://packages.overdrive.pw/ rlw main' | sudo tee --append /etc/apt/sources.list > /dev/null
[sudo] password for finnegan: 
finnegan@finnegan-NV53A ~ $ wget -O /tmp/sub.class1.server.ca.pem https://www.startssl.com/certs/sub.class1.server.ca.pem
--2015-05-30 14:43:13--  https://www.startssl.com/certs/sub.class1.server.ca.pem
Resolving www.startssl.com (www.startssl.com)... 192.116.242.20
Connecting to www.startssl.com (www.startssl.com)|192.116.242.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2090 (2.0K) [application/x509-ca-cert]
Saving to: ‘/tmp/sub.class1.server.ca.pem’

100%[======================================>] 2,090       3.14KB/s   in 0.7s   

2015-05-30 14:43:15 (3.14 KB/s) - ‘/tmp/sub.class1.server.ca.pem’ saved [2090/2090]

finnegan@finnegan-NV53A ~ $ wget --ca-certificate=/tmp/sub.class1.server.ca.pem -O - https://secure.overdrive.pw/repo.gpg.key | sudo apt-key add -
--2015-05-30 14:43:43--  https://secure.overdrive.pw/repo.gpg.key
Resolving secure.overdrive.pw (secure.overdrive.pw)... 2600:3c01::f03c:91ff:fe37:5e20, 45.79.66.40
Connecting to secure.overdrive.pw (secure.overdrive.pw)|2600:3c01::f03c:91ff:fe37:5e20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1715 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

100%[======================================>] 1,715       --.-K/s   in 0s      

2015-05-30 14:43:44 (186 MB/s) - written to stdout [1715/1715]

OK
finnegan@finnegan-NV53A ~ $ sudo apt-get install roblox-linux-wrapper
Reading package lists... Error!
E: Type 'wget' is not known on line 5 in source list /etc/apt/sources.list
E: The list of sources could not be read.
E: The package lists or status file could not be parsed or opened.
finnegan@finnegan-NV53A ~ $

**Comment by GLolol** [comment]
What does your `/etc/apt/sources.list` look like?

**Comment by josephskimber** [comment]
Here ya go GLolol, Its a bit above my paygrade.


deb cdrom:[Linux Mint 17.1 _Rebecca_ - Release amd64 20141126]/ trusty contrib main non-free
# # 
# # 

wget -O /tmp/sub.class1.server.ca.pem https://www.startssl.com/certs/sub.class1.server.ca.pem

wget -O /tmp/sub.class1.server.ca.pem https://www.startssl.com/certs/sub.class1.server.ca.pem
wget --ca-certificate=/tmp/sub.class1.server.ca.pem -O - https://secure.overdrive.pw/repo.gpg.key | sudo apt-key add -
sudo apt-get install roblox-linux-wrapper
git clone https://github.com/roblox-linux-wrapper/roblox-linux-wrapper.git

deb http://packages.overdrive.pw/ rlw main
new line of text

**Comment by GLolol** [comment]
I don't know how on earth you managed to get all that in there. Commands don't belong in `sources.list`, only the actual repository link. It should look something like this:

```
deb cdrom:[Linux Mint 17.1 _Rebecca_ - Release amd64 20141126]/ trusty contrib main non-free
# # 
# # 

deb http://packages.overdrive.pw/ rlw main
```

**Comment by josephskimber** [comment]
hmm. Ill back track.

**Comment by josephskimber** [comment]
i have to reistall linux. its an update issue

**Comment by GLolol** [comment]
...No you don't? This has nothing to do with reinstalling. Somehow you managed to break your `sources.list` :|

Replace it with the one I mentioned above and you should be fine.

**Comment by josephskimber** [comment]
Ok

**Comment by josephskimber** [comment]
Please repost the source list it should be. its not working

**Comment by GLolol** [comment]
https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/issues/115#issuecomment-107076540

**Comment by josephskimber** [comment]
Now I get this:
finnegan@finnegan-NV53A ~ $ apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

**Comment by GLolol** [comment]
Run the command as root? **sudo** apt-get update ???

**Comment by josephskimber** [comment]
now we're getting somwhere

**Comment by Kosti1** [comment]
Wine error 1.
fixme:winediag:start_process Wine Staging 1.7.44 is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
regsvr32: DLL:n '' lataaminen epõonnistui

**Comment by skullbro** [comment]
sadly i guess we shall never play roblox again

**Comment by GLolol** [comment]
@skullbro Comments like that aren't helpful.

@Kosti1 I can't understand the error message because it's not in English. Try running `rlw` as `LC_ALL=C rlw` so that the messages output as English.

**Comment by Kosti1** [comment]
Here
----------


Roblox Linux Wrapper 2015.05.28
wine path set to /usr/bin/wine
wineboot path set to /usr/bin/wineboot
wineserver path set to /usr/bin/wineserver
 > begin roblox-install ()
---
 > end roblox-install ()
---
 > begin main ()
---
 > begin playerwrapper ()
---
 > begin rwine ()
---
err:menubuilder:init_xdg error looking up the desktop directory
regsvr32: Failed to load DLL ''

**Comment by alfonsojon** [comment]
@Kosti1 Please don't use large text like that, and wrap logs in three backticks (```). Have you tried the reinstall option?

**Comment by Kosti1** [comment]
I got it working but i joined to this game: http://www.roblox.com/games/217634472/2-Player-Combat-mining-Tycoon-TESTING-SERVER



AND CRASH!


Log:

fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
err:ntdll:RtlpWaitForCriticalSection section 0x17e0060 "heap.c: HEAP.critSection" wait timed out in thread 0096, blocked by 009d, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x17e0060 "heap.c: HEAP.critSection" wait timed out in thread 0075, blocked by 009d, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x17e0060 "heap.c: HEAP.critSection" wait timed out in thread 00b4, blocked by 009d, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x17e0060 "heap.c: HEAP.critSection" wait timed out in thread 0072, blocked by 009d, retrying (60 sec)
fixme:win:FlashWindowEx 0x33ed7c
err:ntdll:RtlpWaitForCriticalSection section 0x17e0060 "heap.c: HEAP.critSection" wait timed out in thread 0054, blocked by 009d, retrying (60 sec)
^Cfixme:console:CONSOLE_DefaultHandler Terminating process a3 on event 0
fixme:console:CONSOLE_DefaultHandler Terminating process 57 on event 0
fixme:msvcrt:__clean_type_info_names_internal (0x3cc398) stub
fixme:msvcrt:__clean_type_info_names_internal (0x2a9e294) stub
fixme:msvcrt:__clean_type_info_names_internal (0x391360) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a9fb454) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a8c6354) stub
fixme:msvcrt:__clean_type_info_names_internal (0x2e615c4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x10003340) stub
fixme:msvcrt:__clean_type_info_names_internal (0x358754) stub
fixme:console:CONSOLE_DefaultHandler Terminating process 8 on event 0
fixme:msvcrt:__clean_type_info_names_internal (0xd545308) stub
fixme:msvcrt:__clean_type_info_names_internal (0xd4d0830) stub
fixme:msvcrt:__clean_type_info_names_internal (0xa9d53a8) stub
fixme:msvcrt:__clean_type_info_names_internal (0xa9b36b4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3cb5c8) stub
fixme:msvcrt:__clean_type_info_names_internal (0x2b4e294) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a9fb454) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a8c6354) stub
fixme:msvcrt:__clean_type_info_names_internal (0x383340) stub
fixme:msvcrt:__clean_type_info_names_internal (0x371360) stub
fixme:msvcrt:__clean_type_info_names_internal (0x8915c4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x10018754) stub
 > begin rwineserver ()
---
err:ntdll:RtlpWaitForCriticalSection section 0x17e0060 "heap.c: HEAP.critSection" wait timed out in thread 0066, blocked by 009d, retrying (60 sec)

**Comment by GLolol** [comment]
Update: ROBLOX seems to be broken on both Wine and Wine Staging 1.7.46. Ping @alfonsojon

**Comment by alfonsojon** [comment]
Thanks for the ping, I will look into it.

**Comment by alfonsojon** [comment]
@GLolol "[July 02, 2015 ( 0.201.1.61043 → 0.202.0.61076 ) - Added EnumItem Platform.Linux](http://anaminus.github.io/api/diff.html#v0.202)"

This may mean a native Linux client is coming soon, although DOS is now apparently a supported platform via their API.

**Comment by ExtaHax** [comment]
When will the crashing be fixed? Have you guys figured out what is wrong with the wrapper you probably dont have a lot of time to fix it but try lol.

**Comment by GLolol** [comment]
It's not a problem with the wrapper when the game crashes; it's a problem with Wine.

**Comment by Z0MBIE2** [comment]
Yo, so roblox crashes and I'm pretty sure I know what's wrong but not exactly. There's a line in there I'm pretty sure is the problem, a missing directory thing, but I'm not sure how to fix it or 100% what it is. 

```
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb08 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f958 1 C) semi-stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f510 1 C) semi-stub
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_0373C 0, 202, 0, 61121.Client.dmp
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_0373C.txt
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_0373C_1.txt
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_0373C_G3D.txt
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_0373C_Roblox TaskScheduler Thread 1_112.txt
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_0373C_CrashReporter_WatcherThreadFunc_191.txt
fixme:wininet:get_proxy_autoconfig_url no support on this platform
```
I think the problem is this specifically
```
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
```
Yet I'm not sure what to do to fix this. 
I'm running 

RLW is unknown, probably the newest though, as the commands don't work so I can't check. 
Wine: 1.7.44
OS Ubuntu 14.10
CPU 64bit
4x Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz

**Comment by GLolol** [comment]
@Z0MBIE2 try `sudo apt-get install libp11-kit-gnome-keyring:i386 p11-kit-modules:i386`

Source: https://askubuntu.com/questions/402500/wine-cant-load-module-p11-kit-trust-so

**Comment by Z0MBIE2** [comment]
```
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fda0 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb08 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f958 1 C) semi-stub
C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f510 1 C) semi-stub
fixme:win:EnumDisplayDevicesW ((null),0,0x33e768,0x00000000), stub!
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f624 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f66c 1 C) semi-stub
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_C4B2F 0, 202, 0, 61121.Client.dmp
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f0a8,0x00000000), stub!
fixme:thread:start_thread Started native thread 00000149
fixme:thread:start_thread Started native thread 0000014a
fixme:thread:start_thread Started native thread 0000014b
fixme:thread:start_thread Started native thread 000000e7
fixme:thread:start_thread Started native thread 000000e9
fixme:thread:start_thread Started native thread 000000ea
fixme:thread:start_thread Started native thread 000000ec
fixme:thread:start_thread Started native thread 000000ed
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x577e968): stub
fixme:win:EnumDisplayDevicesW ((null),0,0x33ed98,0x00000000), stub!
fixme:win:RegisterDeviceNotificationW (hwnd=0x800ca, filter=0x9a7e8e8,flags=0x00000000) returns a fake device notification handle!
fixme:winsock:WS_setsockopt IP_DONTFRAGMENT is silently ignored!
fixme:winsock:WS_setsockopt IP_DONTFRAGMENT is silently ignored!
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_C4B2F_1.txt
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_C4B2F.txt
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_C4B2F_unnamed thread_250.txt
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
Uploading C:\users\z0mbie2\Local Settings\Application Data\Roblox\logs\log_C4B2F_CrashReporter_WatcherThreadFunc_82.txt
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date forma
```

Well, thank you as it no longer shows that in logs. Sadly it wasnt the problem and it still crashes, logs are above.

**Comment by Arandomgithubber** [comment]
I launched roblox countless times. I can't get a screenshot but I think it's roblox's fault now.
This is what I saw in the dev console
"failed to load http://:"
I've heard reports of crashing on windows machines from a single source on youtube:
https://www.youtube.com/watch?v=UeQXSqavyA4
But judging it crashes on all the windows boxes in my house, I think we should just launch studio and play using the multiplayer studio plugin. It would be more stable than the current terrible (Roblox-Based) client. I wish someone had the time to reverse-engineer roblox, and make an open-source version. I know it will never happen. I'm not going to play roblox without multiplayer studio until this is fixed (Which it probably won't be)

**Comment by Z0MBIE2** [comment]
Just to be clear... you are using linux right.

**Comment by Arandomgithubber** [comment]
Yes, I am. The same issue appears on windows.

**Comment by media203** [comment]
When the Roblox Crashed i found this 
" 0000000) returns a fake device notification handle!
fixme:winsock:WS_setsockopt IP_DONTFRAGMENT is silently ignored!
fixme:winsock:WS_setsockopt IP_DONTFRAGMENT is silently ignored!
fixme:wininet:get_proxy_autoconfig_url no support on this platform "

**Comment by Chickenmax** [comment]
Hi I tried to change ma image and i cant anyways ma roblox crashed long time ago IT first tell "An Unexpected error occurred and ROBLOX needs to quit" now it says  "This game has shut down"

BUT ALFONSOJON i think that wine is not so powerfull to run new roblox updates so ALFONSOJON PLIZ DO roblox linux  wrapper but NOT on WINE  DO IT ON a VIRTUAL BOX IT work on a virtual box I
think SO alfonosjon PLIZ do it on dat virtual box just put the comands to us to run and get all stuff ready to play =D

**Comment by Chickenmax** [comment]
virtual boxes CAN run HALF-LIFE it is an old game like roblox so it should run roblox too AND WE WILL PLAY ROBLOX AGAIN YAY =D im almost sure that virtual box is powerful enough to run roblox SO pliz try it PLIZZZ

**Comment by alfonsojon** [comment]
@Chickenmax Some problems with that approach:
1. That would require a paid Windows license $99.99 minimum
2. That would also require a computer that can run a virtual machine well, which are expensive
3. Additionally, a graphics card that can be emulated well would be mandatory.
4. I can't legally distribute copies of Windows. Wine is much faster, and free.

To make a long story short, it would be illegal for us to do that, and it would also run more slowly. If you want a solution like that, you can always install Windows into a virtual machine, or run a Windows computer.

**Comment by Chickenmax** [comment]
OH ok but dud i have a virtual machine WITH options to install windows or mac or LINUX AND its FREE

**Comment by Chickenmax** [comment]
its name is Oracle VM VirtualBox

**Comment by Chickenmax** [comment]
YEA BUT I HAVE 1 problem  ......................................... IDK how to use it

**Comment by Chickenmax** [comment]
UR A PRO ON LINUX and u know WAT TO DO so u can put the comands or something to us to do so we can get ready to play roblox

**Comment by alfonsojon** [comment]
@Chickenmax Windows is not free. Installing OS X on a virtual machine is against the OS X terms and conditions, and probably illegal.

**Comment by alfonsojon** [comment]
@Chickenmax [Your solution is here](http://www.google.com/search?q=how+to+install+windows+in+virtualbox).

**Comment by Chickenmax** [comment]
WELL idk i have dat virtual box and it run windows but IDK how to configur it

**Comment by alfonsojon** [comment]
@Chickenmax We do not support VirtualBox, see the link above to figure out how to set up Windows in VirtualBox.

**Comment by Chickenmax** [comment]
OK in conclusion I GOT WINDOWS ON dat virtual box but idk how to configure ma windows and that virtual box ITS FREE and thx for da link

**Comment by alfonsojon** [comment]
@Chickenmax Again, our product is not VirtualBox based and does not support its usage.

**Comment by Chickenmax** [comment]
ok

**Comment by Chickenmax** [comment]
i just was givin an option

**Comment by Z0MBIE2** [comment]
Why do I have 50 emails telling me someone was trying to talk about the use of virtual box here yet there's no comments?

**Comment by alfonsojon** [comment]
@Z0MBIE2 It was a lengthy and space-taking discussion about VirtualBox, which is not what this issue is for. I cleared them out as they contributed nothing to the discussion.

**Comment by GLolol** [comment]
ROBLOX won't run at all in a Windows VM; the graphics drivers it needs simply don't exist. Believe me, I've tried.

**Comment by Chickenmax** [comment]
LOL im not a linux or wine pro but wine translate the windows script to linux script cause theyre different  so i think that roblox doesnt work because wine cant translate the windows script from roblox to linux script because roblox get updates very often so wine cant understand dem (DIS IS WAT I THINK)

**Comment by Z0MBIE2** [comment]
You mean... you think roblox isn't working... because wine isn't able to make the windows version compatible with linux? Someone please just ban this guy from the discussions...

**Comment by RoblocManiac1234** [comment]
Uh maybe its not the right wine we're using. DirectX is something that has problems in Wine WIndows Program Loader and we might need to get a better version of wine in order to probrably fix this piece junk.

**Comment by RoblocManiac1234** [comment]
Or maybe we could put it on steam and it might work.

**Comment by alfonsojon** [comment]
@RoblocManiac1234 Unfortunately it is not that easy.

**Comment by RoblocManiac1234** [comment]
If we were to use wine 1.8 people would need 64bit-86bit To even play roblox But, You can 32bit libraries can be loaded from 64bit libraries. But, also it uses direct3d so would that have a effect on roblox? 

But, for the most part I found something about graphics in wine 1.8, Animated GIFs are correctly supported in GdiPlus.

**Comment by GLolol** [comment]
Crashes don't seem to happen anymore, we're looking at #135 now.
