### ISSUE TITLE
Glitching: roblox linux wrapper

### ISSUE THREAD

**Issue by richdude464** [roblox-linux-wrapper/roblox-linux-wrapper#118]
on my crouton ubuntu 14.04 lts os roblox freezes up

**Comment by alfonsojon** [comment]
‎Robots for Linux is not supported under crouton.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: richdude464Sent: Tuesday, June 2, 2015 6:50 PMTo: roblox-linux-wrapper/roblox-linux-wrapperReply To: roblox-linux-wrapper/roblox-linux-wrapperSubject: [roblox-linux-wrapper] Glitching: roblox linux wrapper (#118)on my crouton ubuntu 14.04 lts os roblox freezes up

—Reply to this email directly or view it on GitHub.

**Comment by GLolol** [comment]
Closing as this is an unsupported configuration. In the future, please include the following information in your issues, or it may be closed as lacking information! https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/CONTRIBUTING.md#information-needed-in-a-bug-report

For crash bugs in general, we have a meta issue at #115. Please use that for filing information on crashes.
