### ISSUE TITLE
Something :(

### ISSUE THREAD

**Issue by Kosti1** [roblox-linux-wrapper/roblox-linux-wrapper#119]
I did something wrong :(

wine: cannot find '/home/kosti/.local/share/wineprefixes/roblox-wine/drive_c/users/kosti/Local Settings/Application Data/RobloxVersions/RobloxStudioLauncherBeta.exe'

**Comment by GLolol** [comment]
Try the Reinstall Roblox option.

**Comment by Kosti1** [comment]
i did

**Comment by Kosti1** [comment]
nothing happened

**Comment by GLolol** [comment]
Can you be a bit more specific? It shouldn't just "do nothing". If you think this is truly a bug, please at least include the information mentioned here: https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/CONTRIBUTING.md#information-needed-in-a-bug-report

**Comment by Kosti1** [comment]
Ok. i fixed it :)
i just used reinstall roblox option (Also reinstalled RLW)
