### ISSUE TITLE
ROBLOX Universe feature joining as guest

### ISSUE THREAD

**Issue by StripedFelines** [roblox-linux-wrapper/roblox-linux-wrapper#120]
## Description

When I can get the ROBLOX client working at all, if I join a game with universe support (basically lets you put a bunch of places into one game) when you're switching servers it will connect you as a guest.

[I asked Twitter about this to see if it's reproducing on Windows](https://twitter.com/StripedFelines/status/606980859204403201), however I cannot reproduce it on my Windows PC 
## Reproduction

When I joined [The Quarry](http://www.roblox.com/games/151670365/The-Quarry-JW) I can join the starting place fine, where you can choose what edition of the game you want to play. However when I actually go to the game it makes me join as a guest.
## Specifications 

Ubuntu 14.04 (stock) 
Latest Wine + RLW (deb version) 
This is happening on Wine, not Wine-Staging (can't even load the game on WS)

**Comment by alfonsojon** [comment]
Have you tried playing through the Roblox Studio? I have not tested for myself, but I hear that works.

**Comment by StripedFelines** [comment]
I can't launch games from Studio, asks me to download it. @alfonsojon

**Comment by alfonsojon** [comment]
Darn; I will look into this issue when I get home.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                  ‎

**Comment by GLolol** [comment]
Confirming this is an issue: crashing on Wine Staging 1.7.46. Will look into it now.

**Comment by alfonsojon** [comment]
@StripedFelines I thought that playing through the studio would still work, but it would seem I am mistaken.

**Comment by StripedFelines** [comment]
I haven't been on any Linux distros for the past while - having AMD driver issues. This bug may be fixed for all I know, but I can't test at the moment.

**Comment by GLolol** [comment]
Guest mode doesn't seem to be a thing anymore, closing this old issue.
