### ISSUE TITLE
Handle unreachable host errors correctly

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#121]
The Roblox Linux Wrapper should check that the download servers are online and accessible before attempting to download. This can be implemented by providing a specific dialog when wget presents an error code indicating the host is not reachable.

**Comment by GLolol** [comment]
Which download servers in particular?

**Comment by alfonsojon** [comment]
Firefox and the Roblox setup servers.

**Comment by alfonsojon** [comment]
@GLolol Can you test ed0c174ab0e664ccca6f83e745508384ee458cc5 for me? I did some "blind" coding - no linting, no testing - as I am currently at college on my ARM Chromebook, so testing is out of the question for me.

**Comment by GLolol** [comment]
I'll look at it later tonight then.

**Comment by alfonsojon** [comment]
Thanks.

**Comment by alfonsojon** [comment]
Hopefully, this will help us in the event that a user files a bug report and it is actually his or her connection. We then won't have to waste time trying to diagnose an issue that is not even our own.

**Comment by GLolol** [comment]
I'm pretty sure wget makes it obvious when a connection has failed.

**Comment by alfonsojon** [comment]
@GLolol It definitely does, but the rwget function was hiding it. In any situation of a failure, it would return a download error without specifying what exactly went wrong. It now specifies what happened on the wget side of the program.

**Comment by GLolol** [comment]
I feel `rwget` is quite broken in itself, because it only works for downloading single files. The only instance of it being used is for `RobloxPlayerLauncher.exe`, while the Firefox fetcher doesn't work at all because it shows multiple progress bars throughout.

**Comment by alfonsojon** [comment]
@GLolol Would you consider a Vala port?

**Comment by alfonsojon** [comment]
@GLolol https://en.wikipedia.org/wiki/Vala_(programming_language)

**Comment by GLolol** [comment]
I have never touched Vala before.

Or GTK-anything much, for that matter.

**Comment by alfonsojon** [comment]
I've intended on learning Vala, so I'll probably get started with that. If I do make a port, it probably will not be usable any time soon, as virtually any object-oriented language is new to me.

**Comment by GLolol** [comment]
wget output is harder to parse than it looks. I don't /really/ think a wrapper around it is necessary, but whatever.

**Comment by alfonsojon** [comment]
I did not mean a wrapper for it, I meant a native code alternative that we can use internally

**Comment by GLolol** [comment]
A native file downloader?

**Comment by alfonsojon** [comment]
Yeah, something that doesn't make use of wget or curl.

**Comment by alfonsojon** [comment]
@GLolol I know, but I just like Vala for some reason, probably the syntax and what not.

**Comment by alfonsojon** [comment]
Scope creep. Way out of scope for the project; closed.
