### ISSUE TITLE
Better handle multiple wine versions

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#124]
I discovered that there is a package called [`wine-staging-compat`](https://github.com/wine-compholio/wine-staging/wiki/Installation) (see Debian installation), which makes wine-staging the default build of wine in place of wine. I was wondering if we could somehow automatically determine whether or not the installed build of wine is wine or wine-staging, as they both can be installed to `/usr/bin/wine` now. This way, we can apply wine version specific patches, regardless of the default build of wine installed.

**Comment by GLolol** [comment]
The preferred way would be to only show wine paths that exist on the system, but Zenity doesn't make dynamic lists very convenient to handle. I'm thinking of rewriting the Winechooser part separately in Python-gi (GTK3) or something similar, and using bigger buttons for the main design and a description for each choice:

- **/usr/bin/wine**<br>The default, stable installation of Wine. Staging/compholio patches: **True/False** (detect this using the version string)
- **/opt/wine-staging/bin/wine**<br>Wine staging. This is pre-release software - &lt;insert some description here&gt;

**Comment by GLolol** [comment]
Some distros package Wine-staging as `/usr/bin/wine`, so it's not only `wine-staging-compat` that does this. Detecting Wine staging could be  done by just looking for "staging" in the `wine --version` output.

**Comment by alfonsojon** [comment]
I feel as though this script is getting to the point where a more native language may be necessary sooner or later. Zenity isn't advanced enough for what I would like to do.

**Comment by alfonsojon** [comment]
Perhaps we could write the wine version chooser in another language, and call it with the script? It then can act similarly to a built-in function, with the wrapper being able to call the version chooser and be returned the chosen version.

**Comment by GLolol** [comment]
That was my idea.

**Comment by alfonsojon** [comment]
Well then you have a great idea. Are you able to write the version chooser, and should the code be in its own repository?

**Comment by GLolol** [comment]
I'll likely make a `lib/` folder in the main repository. I sort of want to redo the build system with a distro-independent makefile while I'm at it, instead of just telling the `debian/` folder to put things in various places.

**Comment by alfonsojon** [comment]
Alright, great

**Comment by GLolol** [comment]
Update: The version chooser is adequate for now. Debian stretch and later will have [alternatives](https://wiki.debian.org/DebianAlternatives) set in place so "/usr/bin/wine" can be linked to either of their officially packaged versions.
