### ISSUE TITLE
Enable graphical improvements on wine-staging by default

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#125]
`wine-staging` recently added performance enhancing settings, which should most definitely be enabled by default. The wrapper should enable CSMT, as well as ensure CUDA and PhysX are working correctly. This will hopefully improve the performance of the game for many, and may even reduce the frequency of crashes.

Here's a list of things that we can implement:
- [CSMT](https://github.com/wine-compholio/wine-staging/wiki/CSMT)
- [CUDA support](https://github.com/wine-compholio/wine-staging/wiki/CUDA)
- [PhysX acceleration support](https://github.com/wine-compholio/wine-staging/wiki/PhysX)
- [Some useful documentation on advanced wine-staging usage](https://github.com/wine-compholio/wine-staging/wiki/Usage)

**Comment by GLolol** [comment]
Does the ROBLOX client support these at all?

**Comment by alfonsojon** [comment]
Yes, these are wine side changes that improve performance universally.

**Comment by media203** [comment]
Doesnt it support AMD? because i have AMD

**Comment by alfonsojon** [comment]
@media203 No, PhysX is an Nvidia technology.

**Comment by alfonsojon** [comment]
this all can be configured through winetricks, so there is no need for us to enable these by default due to their unstable nature. closed
