### ISSUE TITLE
Bizarre Studio bug w/ Unity Ubuntu

### ISSUE THREAD

**Issue by StripedFelines** [roblox-linux-wrapper/roblox-linux-wrapper#126]
No matter how many times I reinstall it (both Wine and RLW) I get this issue.

ROBLOX Studio shows twice in the window list bar | [screenshot](http://i.imgur.com/NECej0v.png)

When I attempt to click both, only the bottom one works. All the same options are available on the top one but nothing I can do about it, if I close Studio they both are gone.

ROBLOX Studio itself is working fine, and other applications under Wine don't do this. Just sort of a annoyance.

Ubuntu 14.04 (latest Unity) | Latest Wine1.7 + RLW

**Comment by GLolol** [comment]
Some applications do this on Windows too, mind you. It's probably caused by Studio spawning a subprocess to do its work, in which case it wouldn't /really/ be a RLW issue. I'll leave this open anyways.

> Ubuntu 14.04 (latest Unity) | Latest Wine1.7 + RLW

Please be more specific: use `wine --version` to find the Wine version and check your RLW version by starting the app.

**Comment by StripedFelines** [comment]
I can't reproduce it on my Windows PC. Also:

Wine: ```wine-1.7.44```
rlw: ```2015.06.16```

**Comment by alfonsojon** [comment]
This is an issue that is out of our control, as Windows subprocesses work differently than Linux subprocesses. When a wine app starts a subprocess, your environment (Unity) may be reading it as two individual programs. The only "solution" I can see for this is to not use Unity (???), but that is definitely *out* of the question.

**Comment by StripedFelines** [comment]
I have been able to merge them into 1 icon for a few times, I might find a specific pattern to reproduce it.

Anywho, for now, feel free to close the issue.
