### ISSUE TITLE
Soft-depend upon winbind

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#129]
To fix the ntlm_auth "issue", [we must depend upon the winbind package](http://wiki.winehq.org/NtlmAuthSetupGuide).

**Comment by GLolol** [comment]
Already done in 48a27ac501f2ea56672763dce965200f0d3ca20c.

**Comment by alfonsojon** [comment]
@GLolol My bad, I run from source so I couldn't tell
