### ISSUE TITLE
UPDATE: Roblox Linux Wrapper crash 

### ISSUE THREAD

**Issue by media203** [roblox-linux-wrapper/roblox-linux-wrapper#130]
I got this bug and i had this while on Legacy

fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000ae
fixme:thread:start_thread Started native thread 000000af
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b39e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x200c4, filter=0x1bb9e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x300c4, filter=0xf37e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000bb
fixme:thread:start_thread Started native thread 000000bc
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b09e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x400c4, filter=0x1b89e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x500c4, filter=0xf1ee8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000ce
fixme:thread:start_thread Started native thread 000000cf
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b29e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x600c4, filter=0x1ba9e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x700c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000a9
fixme:thread:start_thread Started native thread 000000a8
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b29e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x800c4, filter=0x1ba9e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x900c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000b6
fixme:thread:start_thread Started native thread 000000a9
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b39e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0xa00c4, filter=0x1bb9e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0xb00c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000c0
fixme:thread:start_thread Started native thread 000000bb
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b19e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0xc00c4, filter=0x1b99e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0xd00c4, filter=0xf2de8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 00000062
fixme:thread:start_thread Started native thread 000000c0
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b19e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0xe00c4, filter=0x1b99e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0xf00c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:FlashWindowEx 0x335320
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 0000009d
fixme:thread:start_thread Started native thread 000000aa
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b49e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1000c4, filter=0x1bc9e8f8,flags=0x00000000) returns a fake device notification handle!
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1100c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000b6
fixme:thread:start_thread Started native thread 000000b8
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b49e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1200c4, filter=0x1bc9e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1300c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000d4
fixme:thread:start_thread Started native thread 00000099
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b4ae978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1400c4, filter=0x1bcae8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1500c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000b1
fixme:thread:start_thread Started native thread 000000d9
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1babe978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1600c4, filter=0x1d08e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1700c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 0000009d
fixme:thread:start_thread Started native thread 000000ce
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b7ae978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1800c4, filter=0x1c57e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1900c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:FlashWindowEx 0x334160
fixme:win:FlashWindowEx 0x331a60
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:FlashWindowEx 0x334160
fixme:win:FlashWindowEx 0x331a60
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:FlashWindowEx 0x334160
fixme:win:FlashWindowEx 0x331a60
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000d3
fixme:thread:start_thread Started native thread 000000db
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1b97e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1a00c4, filter=0x2568e8f8,flags=0x00000000) returns a fake device notification handle!
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1b00c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000ac
fixme:thread:start_thread Started native thread 000000d4
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1ba2e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1c00c4, filter=0x2578e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1d00c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:imm:NotifyIME IMC_SETCANDIDATEPOS
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 000000a4
fixme:thread:start_thread Started native thread 000000cb
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1bd6e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x1e00c4, filter=0x25b1e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x1f00c4, filter=0x1949e8f8,flags=0x00000000) returns a fake device notification handle!
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:win:FlashWindowEx 0x335320
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:thread:start_thread Started native thread 00000109
fixme:thread:start_thread Started native thread 0000010a
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x1bd6e978): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x2000c4, filter=0x25a8e8f8,flags=0x00000000) returns a fake device notification handle!
fixme:win:FlashWindowEx 0x335320
fixme:win:FlashWindowEx 0x335320
fixme:win:FlashWindowEx 0x335320
fixme:win:FlashWindowEx 0x335320
fixme:win:FlashWindowEx 0x3344e0
fixme:win:FlashWindowEx 0x331de0
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:msvcrt:__clean_type_info_names_internal (0x88a85c0) stub
fixme:msvcrt:__clean_type_info_names_internal (0x89b71b8) stub
> rwine: calling wine with arguments "regsvr32 /i /home/alexander/.local/share/wineprefixes/roblox-wine/drive_c/users/alexander/Local Settings/Application Data/RobloxVersions/version-4b2704791da04c77/RobloxProxy.dll "
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
regsvr32: Successfully registered DLL '/home/alexander/.local/share/wineprefixes/roblox-wine/drive_c/users/alexander/Local Settings/Application Data/RobloxVersions/version-4b2704791da04c77/RobloxProxy.dll'
fixme:msvcrt:__clean_type_info_names_internal (0x1001c398) stub
regsvr32: Successfully installed DLL '/home/alexander/.local/share/wineprefixes/roblox-wine/drive_c/users/alexander/Local Settings/Application Data/RobloxVersions/version-4b2704791da04c77/RobloxProxy.dll'
fixme:msvcrt:__clean_type_info_names_internal (0x1001c398) stub
> rwineserver: calling wineserver with arguments "--wait "
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed

(zenity:10238): Gdk-CRITICAL **: gdk_device_get_n_axes: assertion 'gdk_device_get_source (device) != GDK_SOURCE_KEYBOARD' failed
> rwine: calling wine with arguments "/home/alexander/.local/share/wineprefixes/roblox-wine/drive_c/users/alexander/Local Settings/Application Data/RobloxVersions/version-4b2704791da04c77/RobloxPlayerBeta.exe --id 213261761 "
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fda0 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb08 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f958 1 C) semi-stub
C:\users\alexander\Local Settings\Application Data\Roblox\logs\
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f510 1 C) semi-stub
fixme:win:EnumDisplayDevicesW ((null),0,0x33e768,0x00000000), stub!
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f624 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f66c 1 C) semi-stub
fixme:win:EnumDisplayDevicesW ((null),0,0x33f0a8,0x00000000), stub!
fixme:thread:start_thread Started native thread 00000051
fixme:thread:start_thread Started native thread 00000052
fixme:thread:start_thread Started native thread 00000053
fixme:thread:start_thread Started native thread 00000054
fixme:thread:start_thread Started native thread 00000056
fixme:thread:start_thread Started native thread 00000057
fixme:thread:start_thread Started native thread 00000058
fixme:thread:start_thread Started native thread 00000059
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x57fe978): stub
fixme:win:EnumDisplayDevicesW ((null),0,0x33ed98,0x00000000), stub!
fixme:thread:start_thread Started native thread 0000005d
fixme:win:RegisterDeviceNotificationW (hwnd=0x1005a, filter=0x8dce8f8,flags=0x00000000) returns a fake device notification handle!
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithDataSegs
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fda0 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb08 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f958 1 C) semi-stub
C:\users\alexander\Local Settings\Application Data\Roblox\logs\
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f510 1 C) semi-stub
Uploading C:\users\alexander\Local Settings\Application Data\Roblox\logs\log_87203 0, 202, 0, 61121.Client.dmp
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
Uploading C:\users\alexander\Local Settings\Application Data\Roblox\logs\log_87203_CrashReporter_WatcherThreadFunc_61.txt
Uploading C:\users\alexander\Local Settings\Application Data\Roblox\logs\log_87203.txt
Uploading C:\users\alexander\Local Settings\Application Data\Roblox\logs\log_87203_rbx_BaseThreadPool_40.txt
Uploading C:\users\alexander\Local Settings\Application Data\Roblox\logs\log_87203_1.txt
Uploading C:\users\alexander\Local Settings\Application Data\Roblox\logs\log_87203_G3D.txt

No Wonder why its going to this crashing sometime if i play on wine firefox and like this for example 
"Nightmare ★ Pizzeria 🔥2🔥" and if i play it i get a crash. If this a bug Please fix it. its not my audio it works.

**Comment by GLolol** [comment]
You've already opened an issue about this (#128). Please read the comments there for what to include in a bug report.

There is already a metabug at #115 for crash logs. Post there, and use a pastebin so you don't make the comments extremely long.
