### ISSUE TITLE
Depend upon wine > 1.7.28, or wine-staging > 1.7.28

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#132]
See title. By depending upon a specific version, we don't have to have a version checker within the script.

**Comment by GLolol** [comment]
We already do this? https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/debian/control#L18

Having an internal version checker is good, because not every installs via a `.deb`...

**Comment by alfonsojon** [comment]
@GLolol I was just able to install with Wine 1.6. What I mean is depend upon a specific set of versions, if possible.

**Comment by GLolol** [comment]
That's not possible... You can't depend on both `>= 1.6.2` and `>= 1.7.28` with one package. Things like 1.7.1 will also match.

Edit: I realize just now that Ubuntu uses a package version of `1:1.6.x`.. where the `1:` is an epoch. That's higher than `1.7.28`...

**Comment by alfonsojon** [comment]
Well that would explain how I installed with Wine 1.6.xx... is it possible to deal with this, or is it made that way on purpose?

**Comment by GLolol** [comment]
Not really... It's more because Debian and Ubuntu package Wine separately, so Ubuntu decided to bump their version so it doesn't get overwritten by what Debian has.

**Comment by alfonsojon** [comment]
That also makes sense. So, what can be done about it, if anything?

**Comment by GLolol** [comment]
No... It's not a bug. It's a choice done by the maintainers, and it's perfectly reasonable if you understand the intricacies of packaging.

**Comment by alfonsojon** [comment]
Thank you for explaining, I'm not familiar with debian packaging.
