### ISSUE TITLE
Create Jekyll GitHub pages for documentation and the like

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#134]
There should be a Jekyll-based GitHub page for the Roblox Linux Wrapper. Rather than having many *.md files, we can have an easy-to-use, static page in which users have a simple explanation and download button presented to them.

**Comment by GLolol** [comment]
We only have two files... Is this really necessary?

**Comment by alfonsojon** [comment]
@GLolol It's necessary given the amount of comments and messages I've been getting about how it is not working for them, and the installation instructions were not clear enough. I receive numerous messages weekly from users asking how to install it, even though we provide installation instructions. Most of the issues come from wine being misconfigured, so I'll probably walk through the installation of Wine on the page as well.

**Comment by GLolol** [comment]
*sigh* Still not clear enough? You install a package from a repository and launch the wrapper...

**Comment by alfonsojon** [comment]
@GLolol You'd be surprised...

**Comment by alfonsojon** [comment]
This has been satisfied by the new Wikis feature GitHub introduced.
