### ISSUE TITLE
Game black screens when playing

### ISSUE THREAD

**Issue by GamingCenturari** [roblox-linux-wrapper/roblox-linux-wrapper#139]
I start using roblox and as soon as i get into the game, it will just leave my screen blank. ;-;

**Comment by GamingCenturari** [comment]
I have Ubuntu 14.04
im using wine 1.7.47

**Comment by autospamfighter** [comment]
More information please?

@GLolol Please add needs info tag

**Comment by GamingCenturari** [comment]
Well, I updated my ROBLOX wrapper to the latest version and i think its because of the roblox updates or the fact i don't have a graphics card

**Comment by LunaSquee** [comment]
Run winetricks -> "Select roblox-wine" -> "Change settings" -> Check "ddr=opengl" and press OK.
This should fix the black screen issue.

**Comment by GLolol** [comment]
57ee69f
