### ISSUE TITLE
wineprefix robloxproxy.dll

### ISSUE THREAD

**Issue by Reset2378658** [roblox-linux-wrapper/roblox-linux-wrapper#140]
when i start roblox linux wrapper, it asks me for an option (play roblox, roblox studio, reinstall, etc)
if i click on play roblox, it says "could not find robloxproxy.dll in the wineprefix"
it then tells me to reinstall
when i reinstall, it says "A working roblox wineprefix was not found. Would you like to install one?"
if i click on yes, it says "wineboot closed unsuccessfully. See terminal for details (exit code 1)"
if i click on no, it just closes, and when i reopen it, it asks for the wineprefix again
im using zorin os, and i uninstalled the pre-installed 1.6 wine and installed 1.7
i followed this tutorial: http://roblox.wikia.com/wiki/Install_Roblox_on_Linux

**Comment by GLolol** [comment]
Can you put a full log of your error in a [pastebin](https://gist.github.com)? Namely, the lines up to the "wineboot closed unsuccessfully" error.

**Comment by Reset2378658** [comment]
im new to linux, i dont know where to find the log
i might think its just a zorin-related issue, because other stuff like steam doesn't work properly
i'll try getting elementary os and let you know if the issue is still there

**Comment by Reset2378658** [comment]
i switched to elementary os, seems to work so far

**Comment by alfonsojon** [comment]
Alright, great. I'll close this issue, and you can report any findings on issue #135.
