### ISSUE TITLE
ROBLOX works for a few seconds AND then it says "this game has shut down"

### ISSUE THREAD

**Issue by Chickenmax** [roblox-linux-wrapper/roblox-linux-wrapper#142]
LOL it doesnt works months ago with older wine versions it runned for a few seconds and it said " an unexpeced error has ocurred and roblox needs to quit"  but now it says that IT doesnt work on wine or wine stagging PLIZ HELP

**Comment by GLolol** [comment]
Duplicate of #135... But apparently you were aware of that :|
