### ISSUE TITLE
Reduce modifications needed to run Roblox

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#145]
In an attempt to resolve the issues where Roblox is booting Linux clients from the server automatically, we should find ways to reduce the amount of modifications necessary to run Roblox, such as trying to get VIsual C++ 2010 to work correctly on Wine. Perhaps we should install all dependencies manually?

Edit: Just hoping to find a fix here, these are not likely culprits.

**Comment by GLolol** [comment]
...what.

> In an attempt to resolve the issues where Roblox is booting Linux clients from the server automatically, we should find ways to reduce the amount of modifications necessary to run Roblox

It doesn't matter *how* the environment is "modified", Wine is still not equal to native Windows. How does this make a difference?

> such as trying to get VIsual C++ 2010 to work correctly on Wine.

winetricks vcrun2010?

> Perhaps we should install all dependencies manually?

What benefit would that have?

**Comment by alfonsojon** [comment]
I know it's likely not going to work, but I just really want to get the client working, and the Roblox staff have not been helpful... at all. I don't want this to be the end of the road; the game hasn't worked for over a month now. I simply can't come up with any other solutions to this problem, given that it's not a simple Windows function not implemented in Wine, or that it's not just Roblox having a bug. This is caused by the server not verifying the client as a legitimate player, so this is honestly looking like it's getting out of our control. I'll talk with a wine-staging developer about the issue.

**Comment by GLolol** [comment]
I noticed this in the logs that ROBLOX stores in Application Data:

```
24.08.2015 02:50:03.44920 (0.7898282)Log "rbx_BaseThreadPool"
02:50:03.44920 (0.7898282) Warning: httpGet https://www.roblox.com/Login/Negotiate.ashx?suggest=Guest:-1634440845 failed. Trying again. Error: CURL error (curl_easy_perform, 0462E390): SSL connect error.  Elapsed time: 0.0783257
```

My guess: SSLv3 support was dropped; Wine doesn't implement anything higher, and thus fails to connect to its auth servers.

**Comment by alfonsojon** [comment]
@GLolol You and I both are not Wine developers, but how hard do you think it would be for the Wine team/Wine Staging team to implement a recent version of SSL, provided this is the issue?

**Comment by GLolol** [comment]
It's only a guess; I'm going to try to get some traces now.

**Comment by alfonsojon** [comment]
@GLolol Thanks. My test machine is broken currently.

**Comment by moonshadow565** [comment]
Roblox.com doesnt support sslv3 which is good since sslv3 is considered insecure.
That shouldnt be a problem since TLS1/1.1/1.2 are present on wine/linux and are supported by roblox.com
http://wiki.winehq.org/Secur32

```
[another@localhost ~]$ nmap --script ssl-enum-ciphers -p 443 roblox.com

Starting Nmap 6.47 ( http://nmap.org ) at 2015-08-27 13:21 UTC
Nmap scan report for roblox.com (69.172.201.47)
Host is up (0.054s latency).
PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   SSLv3: No supported ciphers found
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_RSA_WITH_RC4_128_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_RSA_WITH_RC4_128_SHA - strong
|     compressors: 
|       NULL
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_RC4_128_SHA - strong
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|       TLS_RSA_WITH_RC4_128_SHA - strong
|     compressors: 
|       NULL
|_  least strength: strong
```

**Comment by StripedFelines** [comment]
@alfonsojon @GLolol 
>In an attempt to resolve the issues where Roblox is booting Linux clients from the server automatically, we should find ways to reduce the amount of modifications necessary to run Roblox, such as trying to get VIsual C++ 2010 to work correctly on Wine. Perhaps we should install all dependencies manually?

Kind of off topic, but... 

ROBLOX is currently on a roadmap to support Linux clients/SteamOS (One of them I believe.) in the near future (within a year, most likely). They could have intentionally done something to block RLW since they don't want interference.

I'll edit this once I find the link to the source, but recently they updated Enum.Platform to include a roadmap of upcoming platforms (and placeholders) which includes "Android", "SteamOS", and apparently "Linux" itself.

Still working on contacting the engineering team about it.

**Comment by SethDusek** [comment]
@StripedFelines I've talked to roblox developers about the platform thing and it turned out to be a joke.

I've also talked to zeuxcg and maxvee and they are not willing to support linux because:

1) They haven't figured out how to build a version of the roblox player that works across all distros
2) Player base. It probably won't be very profitable porting roblox to linux

**Comment by moonshadow565** [comment]
@SethDusek 
So its same FUD as others

**Comment by alfonsojon** [comment]
Closed as all issues listed require upstream changes.
