### ISSUE TITLE
Can't join any ROBLOX games

### ISSUE THREAD

**Issue by EchoDuplication** [roblox-linux-wrapper/roblox-linux-wrapper#146]
ROBLOX Studio works as intended, but joining any ROBLOX games outputs the following: http://pastebin.com/aP4Z8jsZ and also gives me a program error which outputs: http://pastebin.com/0pTeKWN5

I'm using Manjaro Linux with plasma 5.4, and my hardware specs can be found here: http://pastebin.com/xrP1vphx

This was after a clean install of both wine (wine-1.7.50) and rlw

help?

**Comment by alfonsojon** [comment]
Does the game client open, or does it print "Roblox has countered an error"?

**Comment by EchoDuplication** [comment]
The client never opens, it just says "ROBLOX has encountered an error and needs to quit".

**Comment by ThrownException** [comment]
Try changing the graphics settings in Studio to OpenGL.

**Comment by alfonsojon** [comment]
@EchoDuplication That's actually a good idea; check that you're running in OpenGL mode. DirectX does not work correctly at the moment; if it does work, it's not going to run well.

**Comment by GLolol** [comment]
Confirmed: game client crashes on start (Wine 1.8-rc4).

**Comment by GLolol** [comment]
Client starts fine on Wine 1.9.6 (development version), but #135 still makes games unplayable. Closing
