### ISSUE TITLE
"This Game Has Shutdown"

### ISSUE THREAD

**Issue by ThrownException** [roblox-linux-wrapper/roblox-linux-wrapper#147]
Whenever I join a game, it gives me the message after the game completely loads.

I am running Ubuntu 14.04.3 LTS (fresh install)
I am using a RTL8188ce network card
I am using a Intel Graphics Card (like this matters)
I have 8GB of RAM.

idk what could be causing this. Could it be because I installed wine (the correct version) after installing the wrapper? idk.

**Comment by alfonsojon** [comment]
See issue #135. Closed as duplicate.
