### ISSUE TITLE
When is it coming back?

### ISSUE THREAD

**Issue by nikolaaa4** [roblox-linux-wrapper/roblox-linux-wrapper#149]
Hello. As of september this script doesn't work anymore, will this be fixed soon or not? We all would like to play :(

**Comment by GLolol** [comment]
It's not our fault - and it's probably not the Wine developers' fault either. ROBLOX staff is about is uncooperative as you can get.

**Comment by alfonsojon** [comment]
@nikolaaa4 If I can find an innovation or workaround that will get everything working again, I will gladly implement; however, it seems like the Roblox team is actually working against us.

Unfortunately, there's not much we can do for now.

**Comment by stormchaser3000** [comment]
why would the roblox team be working against us?

**Comment by OTRD5k** [comment]
Good night sweet prince :(

**Comment by HeroCC** [comment]
Any comment on this, @ROBLOX?

**Comment by GLolol** [comment]
Closing as not technically a bug (it's a question which has been answered above)
