### ISSUE TITLE
Every time I click play, roblox opens a new google chrome tab and nothing happens. #GalliumOS

### ISSUE THREAD

**Issue by lorenzow** [roblox-linux-wrapper/roblox-linux-wrapper#152]
I'm using the Gallium OS distro and I have wine 1.8 installed. Whenever I open roblox and I click play on a level, a new tab is opened on google chrome with nothing open. After that happens I click back to the roblox page I was just on and it keeps on saying install to play in a green rectangle. This happens every time I click play. Luckily, roblox studio is up and running and I have a stable 45 fps! Thats crazy for a bay-trail chromebook. I even had shadows on :).

**Comment by lorenzow** [comment]
Wait, nevermind I fixed it. I just had to actually open roblox linux wrapper and install the c++ thing and install mozilla firefox. Hopefully the " This game has ended " bug will be fixed oneday. *sigh*

**Comment by GLolol** [comment]
See #135 for the meta-issue. There's not much we can do to fix the Roblox client, because it doesn't like Wine!
