### ISSUE TITLE
Roblox keeps thinking that I dont have Roblox installed whenever I try and play a game

### ISSUE THREAD

**Issue by vernaloak968** [roblox-linux-wrapper/roblox-linux-wrapper#155]
after i click the game i want then click the green play button it won't let me start without downloading the game again. when i download it and try again i get the same problem,
please help

**Comment by RobloxTechnicalSupport** [comment]
Okay in order to better understand your problem could you please tell me what browser you were using (Firefox, Chrome, Internet Explorer), what operating system (windows 7, 8, 10), and how long you have had this problem (7-10 Days, Etc.).

**Comment by GLolol** [comment]
Something's wrong with the way the proxy DLL is loaded. Legacy Mode still works fine though

**Comment by GLolol** [comment]
Some background: ROBLOX has updated their interface for Firefox to be closer to the Chrome one: https://en.help.roblox.com/hc/en-us/articles/204473560

AFAIK, this means that no plugin is needed anymore, and games are started using a request to the Roblox's (proprietary?) protocol.

**Comment by kkabrams** [comment]
Maybe consider switching to Safari instead of firefox? I modified rlw to use the version of safari that winetricks uses and it at least tried to open Roblox from the webpage, but Roblox still crashed.

**Comment by twkomp** [comment]
Lately i have found out that ROBLOX have indeed removed the `--id` tag. However I found that the `--id` tag have been replaced by `--play`. However, I get an error saying "could not connect to the game, please try again later."

**Comment by KrystianoXPL** [comment]
@GLolol I have written handler for robox-player and roblox-studio protocols. and it works perfectly. when for example I click Edit one one of my places. I'm not sure if it works for roblox player becuase for some reason it crashes (Game window doesn't even popup) I will share it soon

**Comment by GLolol** [comment]
Fixed by #163
