### ISSUE TITLE
Where is ROBLOX installed after running the wrapper?

### ISSUE THREAD

**Issue by DevanWolf** [roblox-linux-wrapper/roblox-linux-wrapper#157]
Where is ROBLOX located from the wrapper? It's not in my wine user folder, I tried searching, but it wasn't there!

**Comment by GLolol** [comment]
`~/.local/share/wineprefixes/roblox-wine`

**Comment by DevanWolf** [comment]
Oh, just letting that for someone who don't know where the program was put before.
