### ISSUE TITLE
Get correct wine

### ISSUE THREAD

**Issue by remivamp** [roblox-linux-wrapper/roblox-linux-wrapper#161]
I'm using wine and it only recognizes the 1.6.3 version of wine. Is there a way I can make it be recognized by the other versions?

**Comment by GLolol** [comment]
What OS are you running? Which Wine versions have you installed?

**Comment by remivamp** [comment]
I was using Zorin OS which is based on UBUNTU at the time.

**Comment by GLolol** [comment]
Ok, but which versions of *wine* have you installed?

**Comment by remivamp** [comment]
1.7 crossover and 1.6 at the time.

**Comment by GLolol** [comment]
Crossover installs its own copy of wine into `/opt` as `/opt/cxoffice/bin/wine` - the latest commit adds this as an option in "Select Wine Release", so choose that and it should run the right version.
