### ISSUE TITLE
Remove redundant functions and simplify the script

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#164]
RLW has a lot of redundant functionality, and can probably be simplified and slimmed down. See #163 for details. (to be revised)

**Comment by alfonsojon** [comment]
See testing branch for changes to resolve this issue.

**Comment by GLolol** [comment]
I've made some more changes here: https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/compare/06927bb...testing

Still to be tested is the actual .deb install / using system/FHS paths.
