### ISSUE TITLE
Packaging must depend upon cabextract

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#165]
Running winetricks causes failures when cabextract is not present. We should require cabextract to be installed on the system.

**Comment by GLolol** [comment]
I think we should stop shipping our own winetricks and just use the upstream one. (Yeah, this is a reversal from what I did way back)

**Comment by alfonsojon** [comment]
By depending on winetricks, that'll depend upon cabextract, correct? I'm not familiar with Debian packaging

**Comment by GLolol** [comment]
Correct, but the current master isn't package ready so that has to be ironed out first.

**Comment by alfonsojon** [comment]
I'll be making my changes in a new testing branch
