### ISSUE TITLE
Install failed missing download

### ISSUE THREAD

**Issue by martinellison** [roblox-linux-wrapper/roblox-linux-wrapper#166]
--2017-04-18 18:54:57--  https://web.archive.org/web/20170416162254/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Reusing existing connection to web.archive.org:443.
HTTP request sent, awaiting response... 404 Not Found
2017-04-18 18:54:58 ERROR 404: Not Found.

------------------------------------------------------
Downloading https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE failed
------------------------------------------------------

**Comment by alfonsojon** [comment]
What system are you running, and what wine version? This can be caused by an old version of Winetricks.

**Comment by GLolol** [comment]
Wine version shouldn't make a difference...

@martinellison Run this command in a terminal and paste the output here: `winetricks --version`

AFAIK this error is a Winetricks bug https://github.com/Winetricks/winetricks/issues/774

**Comment by GLolol** [comment]
This is fixed upstream in Winetricks
