### ISSUE TITLE
"No Robloxproxy.dll in the Wine prefix"

### ISSUE THREAD

**Issue by hyperak** [roblox-linux-wrapper/roblox-linux-wrapper#168]
I have looked into different issues, and did not found anything like my case, at least not completely (#140).

This is my case in a nutshell.
1. Open RLW.
2. Press "Play ROBLOX", "ROBLOX Studio", or whatever.
3. In no time, you will find a message in your screen similar to "Could not find RobloxProxy.dll in the wineprefix."
4. Reinstall ROBLOX.
5. Repeat.

* Ubuntu 17.04 with Budgie DE (Ubuntu Budgie)
* Intel HD Graphics 4000
Oh, I forgot to tell, it is pretty unlikely, but my problem is probably because of the video drivers. Actually, no, because when I was using standard 16.04, the same thing happened.
* No proxy nor VPN
* Wine version 1.8.7
* Chromium

**Comment by angusbeefsteak** [comment]
Yep, I am getting that same issue when trying to run the game. I am also getting issues when I reinstall Roblox.
