### ISSUE TITLE
Has anyone tested this with newer versions of Wine yet?

### ISSUE THREAD

**Issue by devmgran** [roblox-linux-wrapper/roblox-linux-wrapper#169]
I apologize if this is an inappropriate place to ask such a question, but I've really been wanting to play Roblox again; I don't really want to dual boot either. I've already tried VMs (VirtualBox, qemu) and I was able to launch Roblox in qemu, although the performance was pretty unsatisfactory (I don't have a dual GPU setup or anything, just a laptop) and I was having many issues with mouse emulation.

I checked the release notes for Wine-Staging 2.9 and that version seems to include a lot of fixes related to anti-cheat implementations, which seems to be a major inhibitor for getting Roblox to work successfully on Linux.

I only ask this because on WineHQ, the latest version of Wine tested is 1.7.38, which is fairly old now (released on 6 March, 2015!)

**Comment by GLolol** [comment]
I might find time but I'm not incredibly interested in roblox anymore - your best bet is to give it a try yourself :)

**Comment by Nebblez** [comment]
From my testing, it does not seem to work. Hopefully it will be fixed. Or roblox will just stop being lazy losers and release a linux port already haha

**Comment by devmgran** [comment]
I remember poor driver support being an excuse for not porting the game over to Linux, but I don't think this is the case any longer; the open source Mesa drivers for AMD hardware have seen so many improvements in the last few months. The Roblox devs seem to think it would be a waste of money and effort to port the game to Linux, but apparently, a lot of the leg work for porting the game has already been done (i.e., the macOS port). If the Roblox devs were to target only one distribution (Ubuntu and/or Debian), then everyone else could work on packaging the game for other distributions. I'm personally just thinking of playing Minetest from now on, since it's become a very good game in the last few releases. :P

Anyway, that's just me hopping on a soapbox. I'll try the latest Wine version as soon as I get wifi at my house (currently limited to using a phone right now); I'll report my test results on WineHQ when I can.

**Comment by alfonsojon** [comment]
I've tested on Wine 2.21 dev and it works just as poorly. The game loads, but disconnects.
