### ISSUE TITLE
Could not find RobloxProxy.dll in the wineprefix.

### ISSUE THREAD

**Issue by Statonwest** [roblox-linux-wrapper/roblox-linux-wrapper#170]
I continue to get this message even after reinstalling.

**Could not find RobloxProxy.dll in the wineprefix. Please make sure ROBLOX is installed correctly by running "Reinstall ROBLOX".**

**Comment by GLolol** [comment]
Is this fixed in a204100? What version of rlw are you using?

**Comment by Statonwest** [comment]
I just installed the most recent version and continuously got the error. But looking at the page again I see this.

**As of September 2015, this script does not work with the latest versions of ROBLOX. No ETA for a fix is available.**

**Comment by GLolol** [comment]
How did you install rlw? (if it's the apt repo it's somewhat out of date; i'm working on updating it now)

**Comment by Abequinn** [comment]
no .deb file?
