### ISSUE TITLE
Roblox will not open

### ISSUE THREAD

**Issue by FrenotyCoderCuck** [roblox-linux-wrapper/roblox-linux-wrapper#172]
Installed properly and tried playing a game, and when clicked play nothing happened at all :(

**Comment by lmore377** [comment]
Same but the website tells me to download the game (which obviously it is)

**Comment by Dog48** [comment]
yep same here

**Comment by GLolol** [comment]
What browser are you running?

**Comment by codercuckaj1** [comment]
Google Chrome

**Comment by codercuckaj1** [comment]
the account that I added the bug report on is my alt

**Comment by GLolol** [comment]
Ok, are you using the newest build of rlw? Run `rlw --version`

**Comment by sonejizrelax** [comment]
i have the same bug and this is the output: 

`rlw --version
Sourcing /usr/share/roblox-linux-wrapper/data/rlw-core.sh
wine path set to /usr/bin/wine
wineboot path set to /usr/bin/wineboot
wineserver path set to /usr/bin/wineserver
Roblox Linux Wrapper 2017.06.21
`

**Comment by monofur** [comment]
It seems like when launching from Mozilla Firefox, it doesn't launch or attempt to launch the game.
I have it installed correctly, and it seems like it might be the wrapper causing this issue.

If you'd like any commands or output I can provide this, thanks.

**Comment by Menotdan** [comment]
same issue

**Comment by ishland** [comment]
same issue

**Comment by ishland** [comment]
I use Google Chromium. It tells me this page want to open "xdg-open", then I allowed it. And it tells me to install Roblox.

**Comment by jlu5** [comment]
@alfonsojon Please consider archiving this repository under its settings

This project is effectively dead - our experience over the last year is that even if you can get the loader to work, the game won't actually be playable due to strict anti-cheat code somewhere in the stack. I thus don't think this is worth diagnosing further.

**Comment by alfonsojon** [comment]
The issue with the game opening should be fixed, however I do not believe this game will ever reach a playable state due to the anti-cheating code as @jlu5 mentioned.
