### ISSUE TITLE
Unable to launch game Roblox

### ISSUE THREAD

**Issue by coreybruce** [roblox-linux-wrapper/roblox-linux-wrapper#173]
Website asks for me to install roblox  even tho it is installed.

**Comment by GLolol** [comment]
Duplicate of #172

**Comment by CharlesNadolski** [comment]
Same issue.  Installed roblox using the linux wrapper, can't launch a game from Firefox (prompts to download an install roblox).
rlw --version
Sourcing /usr/share/roblox-linux-wrapper/data/rlw-core.sh
wine path set to /usr/bin/wine
wineboot path set to /usr/bin/wineboot
wineserver path set to /usr/bin/wineserver
Roblox Linux Wrapper 2017.06.21
firefox --version
Mozilla Firefox 57.0.3
