### ISSUE TITLE
I found something that may help.

### ISSUE THREAD

**Issue by Slayer501690** [roblox-linux-wrapper/roblox-linux-wrapper#174]
I've been trying to figure out roblox issues in the past few days and i stumbled upon this https://pastebin.com/xFMf8AnL
It seems like directx11 isnt the issue to me. It looks like it reverts to directx9 but roblox doesn't let you in later due to a CURL error. 
Let me know if this helps.

**Comment by monofur** [comment]
I believe this was reported in the original thread (https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/issues/135), so this might already be known.

**Comment by Abequinn** [comment]
Maybe use winetricks to install the DLL's?

**Comment by GLolol** [comment]
directx 11 is [purposely disabled](https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/data/roblox-player.sh#L18) here for reasons I don't exactly remember, but it probably has to do with Wine's DX11 implementation being incomplete/causing issues

**Comment by KrystianoXPL** [comment]
Roblox will run with DX11 but with graphical glitches, the game still shuts down.
