### ISSUE TITLE
Roblox Player Launcher launches, but the game doesn't open

### ISSUE THREAD

**Issue by mrteenageparker** [roblox-linux-wrapper/roblox-linux-wrapper#178]
I seem to have an issue similar to #172 - except the launcher process opens, but with no window, then closes a few seconds later.

I will try building from source to see if it is just the package causing the issue.

**Comment by mrteenageparker** [comment]
Status update: running ROBLOX after running from source just results in it saying "an unexpected error occurred and ROBLOX needs to quit, we're sorry!" on the launcher

**Comment by alfonsojon** [comment]
Does the issue still occur after today's release?

**Comment by alfonsojon** [comment]
Closing due to no update in a very long time
