### ISSUE TITLE
Roblox place launches but gets kicked out of game.

### ISSUE THREAD

**Issue by Redridge** [roblox-linux-wrapper/roblox-linux-wrapper#179]
I can join the games, I even see the chat for a second but then I instantly and automatically get kicked out of the server.

Ideas?

**Comment by GLolol** [comment]
#135

This isn't something we can fix because any server-side checks imposed by Roblox are out of our control.

**Comment by Redridge** [comment]
So are you sure that it has nothing to do with the way roblox launches?
