### ISSUE TITLE
This game has been shutdown

### ISSUE THREAD

**Issue by ikbenalikecall** [roblox-linux-wrapper/roblox-linux-wrapper#181]
![robloxscreenshot20180518_124654564](https://user-images.githubusercontent.com/39406023/40231548-d56779fa-5a9b-11e8-9c86-34a7d7a8687d.png)
Every time I join I get this game stopped for a reason or it has stopped. Do you have an idea what can be? With greeting Ikbenalikecall!

**Comment by GLolol** [comment]
#135

There's probably anti-cheat provisions in the roblox stack that don't quite work yet on Wine
