### ISSUE TITLE
I have some questions....

### ISSUE THREAD

**Issue by AtomynosAtom** [roblox-linux-wrapper/roblox-linux-wrapper#183]
I have setup Roblox on Arch Linux successfully. As in when I click play game on the website it opens Roblox and joins the game. But it kicks me out when I try to join a game.

I wanted to know why does the anti-cheat does so. And can we bypass the anti-cheat? I've played around with some APIs like WeAreDevs. That successfully attaches to Roblox without getting the user kicked.

**Comment by AtomynosAtom** [comment]
I'm not sure if it may help you. But you should take a look at these api's. Like WeAreDevs. They successfully can inject code into the Roblox game Lua and LuaC. Allowing the user to pull of cheats like the CheatEngine speed hacks. If there is some way that you could some how use this and implement it in the Roblox Wrapper and some how make this work. Please let me know.

**Comment by alfonsojon** [comment]
That would not help, and modifications to the game are outside the scope of this project.
