### ISSUE TITLE
VMProtect with Proton?

### ISSUE THREAD

**Issue by TheEssem** [roblox-linux-wrapper/roblox-linux-wrapper#184]
I found this comment on the Proton issue tracker regarding VMProtect: https://github.com/ValveSoftware/Proton/issues/928#issuecomment-520103364

Apparently newer versions of Proton have it working. Has this been tested any?

**Comment by alfonsojon** [comment]
I have tried to test with Proton and have not gotten it to properly launch; however, I believe Proton is our best bet for getting the game working at this point.
