### ISSUE TITLE
Error at hooking API

### ISSUE THREAD

**Issue by RUvlad1** [roblox-linux-wrapper/roblox-linux-wrapper#185]
When I try to play a game, Roblox fails to start giving this error:

Error at hooking API "LdrFindResource_U"
Dumping first 32 bytes:
F3 0F 1E FB E8 C7 57 FC FF 05 37 32 07 00 8D 4C
24 04 83 E4 F0 FF 71 DC 55 89 E5 57 56 53 89 C3

**Comment by T0paz** [comment]
I got the same error, but when I switched the WINE installation to be the Glorious Eggroll fork of Proton, this didn't happen. I'd assume that the same goes for regular proton as well.

**Comment by AtomynosAtom** [comment]
@T0paz, you got roblox to work on linux?

**Comment by T0paz** [comment]
No, unfortunately. I just got past this boot error by using a different version of WINE, but was kicked with the same error everyone else has been getting. So this is useful only under the circumstance that VMProtect magically stops being an issue.

**Comment by alfonsojon** [comment]
@RUvlad1 I am unable to reproduce this on my system; I am using wine-staging version 5.10. What graphics card are you using, and what wine version do you have installed?

**Comment by RUvlad1** [comment]
The issue got fixed after installing Proton
