### ISSUE TITLE
wine: Bad EXE format for Z:\tmp\RobloxPlayerLauncher.exe

### ISSUE THREAD

**Issue by henrydraton** [roblox-linux-wrapper/roblox-linux-wrapper#189]
The following is the exact sequence of events that causes this scenario as determined by testing:

1. rlw invokes "wget http://roblox.com/install/setup.ashx -O /tmp/RobloxPlayerLauncher.exe"

2. a redirect causes the entire download to fail, see the following:

    * (forum post describing issue that led to me realizing what happened)[https://archive.froast.io/forum/81710020]

    * the following terminal output from wget describing how the download went:

> --2020-12-08 13:46:27--  http://roblox.com/install/setup.ashx
> Resolving roblox.com (roblox.com)... 128.116.114.3
> Connecting to roblox.com (roblox.com)|128.116.114.3|:80... connected.
> HTTP request sent, awaiting response... 308 Permanent Redirect
> 2020-12-08 13:46:27 ERROR 308: Permanent Redirect.

     * the following terminal output from running ls and cat that shows it is empty:

> instant@p6837c:/home/instant/Applications$ ls -l -a /tmp/RobloxPlayerLauncher.exe 
> -rwxr-xr-x 1 instant instant 0 Dec  8 13:46 /tmp/RobloxPlayerLauncher.exe
> instant@p6837c:/home/instant/Applications$ cat /tmp/RobloxPlayerLauncher.exe
> instant@p6837c:/home/instant/Applications$ 

3. Wine fails to run the binary since the EXE file is actually empty, see the following:

    * the following terminal output from wine describing how the attempt went (most of it is superfluous and unrelated):

> rwine: calling wine with arguments "/tmp/RobloxPlayerLauncher.exe "
> wine: created the configuration directory '/home/instant/.local/share/wineprefixes/roblox-wine'
> err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> err:ole:get_local_server_stream Failed: 80004002
> err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
> err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
> err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
> err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
> err:ole:get_local_server_stream Failed: 80004002
> Could not load wine-gecko. HTML rendering will be disabled.
> wine: configuration in '/home/instant/.local/share/wineprefixes/roblox-wine' has been updated.
> wine: Bad EXE format for Z:\tmp\RobloxPlayerLauncher.exe.

    * (image showing the graphical output that appears as a result of the failure)[http://imgur.com/7T10mB5l.png]

**The cause of the problem is the way which the download is attempted, thus causing it to fail and the file to remain empty by the time the wrapper tries to run it.**

**Comment by henrydraton** [comment]
Changing line 43 of rlw to say "wget https://setup.rbxcdn.com/RobloxPlayerLauncher.exe -O /tmp/RobloxPlayerLauncher.exe" is a functional workaround.

**Comment by alfonsojon** [comment]
Thanks for the report, I'll update this when I free up tomorrow.

**Comment by alfonsojon** [comment]
Fixed w/latest commit, that was a long "tomorrow" 😆
