### ISSUE TITLE
Patch how to get without compiling 

### ISSUE THREAD

**Issue by theopensour** [roblox-linux-wrapper/roblox-linux-wrapper#194]
Is there anyway to get the rlw patch without compiling wine

**Comment by Nolij** [comment]
Not until it is merged upstream. It will likely be available in wine-staging first.

**Comment by Percslol** [comment]
if you have a arch based system you can install the patch made by the grapejuice community

**Comment by Percslol** [comment]
https://i.imgur.com/rslraYj.png
^^
Here is a screenshot of it working on my arch based pc

**Comment by alfonsojon** [comment]
I'd personally recommend waiting until it is available in wine-staging, though RLW supports using your own build of Wine.

**Comment by wael444** [comment]
> if you have a arch based system you can install the patch made by the grapejuice community
sorry for bothering but, i can't seem to find it anywhere

i have patched wine with the patch given in #191 but wine just crashes, so i would want to see the grapejuice patch

**Comment by Percslol** [comment]
> > if you have a arch based system you can install the patch made by the grapejuice community
> > sorry for bothering but, i can't seem to find it anywhere
> 
> i have patched wine with the patch given in #191 but wine just crashes, so i would want to see the grapejuice patch

https://www.mediafire.com/file/i2ly1q6px2793jt/winepatch.pkg.tar.zst/file
install it using sudo pacman -U winepatch.pkg.tar.zst

**Comment by vchernin** [comment]
The patch should now be in the latest release of wine-devel & wine-staging 6.11. https://www.winehq.org/announce/6.11. It should soon be available in various distro packages (Arch, Fedora) as well as WINE's binary repos. https://wiki.winehq.org/Download
