### ISSUE TITLE
Cursor is locked by game

### ISSUE THREAD

**Issue by alfonsojon** [roblox-linux-wrapper/roblox-linux-wrapper#195]
The cursor gets locked by the game, and cannot be moved, which makes playing the game and clicking UI elements difficult

**Comment by alfonsojon** [comment]
Same

**Comment by officereso** [comment]
Same here. 
OS: 5.10.27-gentoo
WM: dwm
Wine version: 6.11

When the game eats the cursor keyboard inputs are also delayed for me. 

If i had to take a wild shot in the dark guess maybe wine cant handle the mouse input and has to buffer everything, is roblox not releasing the cursor?. Im able to unlock the cursor by going into a different window and re focusing roblox. Only eats my cursor when right clicking to pan the camera.

**Comment by officereso** [comment]
Also happens in first person

**Comment by nttainBaka** [comment]
that happen to me, when i press r mouse click my cursor locks in game

**Comment by guihkx** [comment]
https://bugs.winehq.org/show_bug.cgi?id=51301

**Comment by nttainBaka** [comment]
i ve found way to unlock!!! but its was only tested in my pc (fedora 34) idk if works in other distro but the way i found is pressing alt + tab 2 and it will unlock

**Comment by Vencorr** [comment]
As a workaround, you can use the patch from the [Roblox on Linux fandom page](https://roblox.fandom.com/wiki/Roblox_on_Linux) and compile wine from source. I set the configure prefix to it's own folder (`/opt/wine-rblx/`) and installed it there, and set my rlw to use the wine located there. This prevents it from affecting other games as the [comment here](https://bugs.winehq.org/show_bug.cgi?id=51301#c4) mentions on the bug report.
```
From dba1a3c3bf5946cd766a439b7db4c8965c92f15e Mon Sep 17 00:00:00 2001
From: BrinkerVII <brinkervii@gmail.com>
Date: Sat, 12 Jun 2021 11:00:06 +0200
Subject: [PATCH 2/2] Turbo jank mouse fix

---
 dlls/winex11.drv/mouse.c | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/dlls/winex11.drv/mouse.c b/dlls/winex11.drv/mouse.c
index 42bac332664..0549c2d653b 100644
--- a/dlls/winex11.drv/mouse.c
+++ b/dlls/winex11.drv/mouse.c
@@ -648,6 +648,10 @@ static void send_mouse_input( HWND hwnd, Window window, unsigned int state, INPU
 
     if (!hwnd)
     {
+        if (input->u.mi.dwFlags & MOUSEEVENTF_RIGHTUP) {
+            reset_clipping_window();
+        }
+
         struct x11drv_thread_data *thread_data = x11drv_thread_data();
         HWND clip_hwnd = thread_data->clip_hwnd;
 
-- 
2.32.0```

Some issues I've noticed with it is that the mouse isn't perfect by any means. It seems to re-correct it's position sometimes, but it's a good workaround for now. Not usable by any means generally.

**Comment by RUvlad1** [comment]
> keyboard inputs are also delayed for me.

I don't have that issue.
Also, this problem doesn't happen on Roblox Studio

**Comment by officereso** [comment]
There's a few patches going around on the grapejuce discord. One for 3rd person and one for first person+shift lock. As for people who still have issues with the patch applied it's likely due to low engine FPS. Without a solid 60 FPS input lag should be expected. I recommend you join the grapejuce discord for info on patching wine.

**Comment by NoOneIsFriend3** [comment]
Just try RoJuicer It worked for me it installs newest version of wine tkg + patches and grapejuice is required

**Comment by XOMUS** [comment]
i made a pull request where there is wine with a fix for this problem

**Comment by alfonsojon** [comment]
It seems this doesn't impact me when I am using Wine 7.16 on KDE using Wayland. Can anyone else test this to see if they are still having issues with the cursor locking?

**Comment by guihkx** [comment]
I'm on GNOME 42.4 and this doesn't happen anymore on the experiences I tried, with vanilla Wine 7.16.

Out of curiosity, I downgraded Wine way back to 6.11 (the version [reported](https://bugs.winehq.org/show_bug.cgi?id=51301) to have this issue), and to my surprise, the cursor lock issue doesn't happen on that version either.

This probably indicates the issue was fixed by the Roblox team.

**Comment by alfonsojon** [comment]
Glad you can confirm this! I am going to close this issue, since it affects neither KDE nor GNOME.
