### ISSUE TITLE
WHEN I PRESS R MOUSE CLICK I CANT MOVE MOUSE INSIDE GAME

### ISSUE THREAD

**Issue by nttainBaka** [roblox-linux-wrapper/roblox-linux-wrapper#196]
when i press right click button on my mouse i cant move my cursor after so the only i can play is funkin friday!!

**Comment by nttainBaka** [comment]
_**pls fix this quick or i will cant play roblox **_

**Comment by nttainBaka** [comment]
i was trying to play [this game](https://web.roblox.com/games/20321167/Pilot-Training-Flight-Simulator#) but i cant! i need to move mouse with r button

**Comment by Vencorr** [comment]
Think this is a duplicate of #195.

**Comment by nttainBaka** [comment]
I VE FOUND WAY TO UNLOCKED MOUSE!! i am in fedora 34 so idk if will work in mint ubuntu or any other distro, the way i ve found is press alt + tab 2 times

**Comment by alfonsojon** [comment]
Closed as duplicate of #195

**Comment by nttainBaka** [comment]
what is duplicate?

**Comment by nttainBaka** [comment]
ik what is 
but i mean why you close being duplicate?

**Comment by Vencorr** [comment]
Because it is a duplicate, and there is already a current issue opened about this issue.
