### ISSUE TITLE
Stop Working ... Crash on enter a server

### ISSUE THREAD

**Issue by paradisebird** [roblox-linux-wrapper/roblox-linux-wrapper#201]
Starting firefox via terminal this is the output i hope it helps.

Wine Staging 6.14
Pop OS 21.04 
Kernel 5.11.0-7620-generic

Sourcing rlw-core.sh
> wineinitialize: sourcing /home/hackaru/.rlw/wine_choice
> wineinitialize: source complete
> wineinitialize: wine path set to /opt/wine-staging/bin/wine
> wineinitialize: wineserver path set to /opt/wine-staging/bin/wineserver
> wineinitialize: Wine version wine-6.14 (Staging) is installed
> rwine: calling wine with arguments "/home/hackaru/.local/share/wineprefixes/roblox-wine/drive_c/users/hackaru/AppData/Local/Roblox/Versions/version-dc9e744f72c94313/RobloxPlayerLauncher.exe roblox-player:1+launchmode:play+gameinfo:520DEDCB495A0408D4CA8BD9B6552C0ACFC247C3C0B6C09F7775B90826BA5C018045E93F43A2671CF5BFA0306F612DBAA1ED925A5B76B3E562D5D49361D0B21319E95D4BFEE70F07DFB01DE28586D0CD062516EC4451AFBDAAE5BE4D97A25D72DB62457C8D89EA82E897E7ED45EE4210A2F0E302F3099EF5636923967DA634B1802E938364A22A6F1C3F38598071EF649F353B7ED0FB569F4617A4DE69BE737EA5C14EC5+launchtime:1628814179382+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestGame%26browserTrackerId%3D113309290182%26placeId%3D6299805723%26isPlayTogetherGame%3Dfalse+browsertrackerid:113309290182+robloxLocale:pt_br+gameLocale:pt_br+channel: "
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.14 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0108:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0290FEF8
0100:fixme:file:NtLockFile I/O completion on lock not implemented yet
0128:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0290FEF8
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0120:fixme:file:NtLockFile I/O completion on lock not implemented yet
0120:fixme:process:SetProcessShutdownParameters (00000100, 00000001): partial stub.
0128:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0128:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0128:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0158:fixme:thread:GetThreadUILanguage : stub, returning default language.
0158:fixme:thread:GetThreadUILanguage : stub, returning default language.
0160:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 05E2FEF8
0158:fixme:thread:GetThreadUILanguage : stub, returning default language.
0158:fixme:thread:GetThreadUILanguage : stub, returning default language.
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0158:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0158:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0108:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0108:err:wininet:HTTP_ParseDate unexpected date format L"-1"
0108:fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
0100:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 006FFEAC
0120:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 006FFEAC
> rwineserver: calling wineserver with arguments "--wait "
0158:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0158:fixme:keyboard:LoadKeyboardLayoutW name L"00000409", flags 1, semi-stub!
0158:fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4090409, 0000: semi-stub!
0158:fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different locales not supported
0158:err:ole:com_get_class_object apartment not initialised
Unable to read VR Path Registry from C:\users\hackaru\AppData\Local\openvr\openvrpaths.vrpath
0158:fixme:d3d9:D3DPERF_GetStatus (void) : stub
0228:fixme:service:I_ScRegisterDeviceNotification Notification filters are not yet implemented.
01f0:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0158:fixme:thread:GetThreadUILanguage : stub, returning default language.
0058:fixme:mountmgr:harddisk_ioctl returning zero-filled buffer for IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS
0164:fixme:winsock:WSAIoctl unimplemented ioctl SIO_IDEAL_SEND_BACKLOG_QUERY
0164:fixme:winsock:server_ioctl_sock Unsupported ioctl 120348 (device=12 access=0 func=d2 method=0)
0164:fixme:winsock:WSAIoctl unimplemented ioctl SIO_IDEAL_SEND_BACKLOG_QUERY
0164:fixme:winsock:server_ioctl_sock Unsupported ioctl 120348 (device=12 access=0 func=d2 method=0)
01b0:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithDataSegs
0164:fixme:winsock:WSAIoctl unimplemented ioctl SIO_IDEAL_SEND_BACKLOG_QUERY
0164:fixme:winsock:server_ioctl_sock Unsupported ioctl 120348 (device=12 access=0 func=d2 method=0)
0174:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 074CE7C8
02a4:fixme:thread:GetThreadUILanguage : stub, returning default language.
02a4:fixme:thread:GetThreadUILanguage : stub, returning default language.
02ac:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 05E2FEF8
02a4:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 043DFEAC

###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

Try to reinstall like i have to do with all updates from the roblox launcher and still don't work.

**Comment by paradisebird** [comment]
Instaling Wine-Devel resolve the issue.

Just install Wine-Devel, and reinstall the wrapper and select the devel version of wine !

I hope it help some one

**Comment by Kauanator** [comment]
do i have to use the command: "./rlw" then i select /usr/bin/wine-development? i did this then showed me that is not a valid path

**Comment by paradisebird** [comment]
i use this path on the ./rlw script

/opt/wine-devel/bin

**Comment by paradisebird** [comment]
> do i have to use the command: "./rlw" then i select /usr/bin/wine-development? i did this then showed me that is not a valid path
> 
> i'm using Ubuntu 20.04 lts
> DUDE IT WORKED THANKS. but my mouse cursor get stuck when i pin it to move the camera.
> 
> i installed roblox choosing the option "Automatic detection (via $PATH)" (was the only way, the others were getting error). so, it installed roblox and sent to own file on roblox-linux-wrapper.

Mouse cursor get stuck is a know issue, and was a patch to wine that kinda worked... until we need to use wine-devel versions

but u have to compile wine by yoruself

i use gamepad for that problem.

**Comment by nttain** [comment]
how do i open the ./rlw file on fedora?
