### ISSUE TITLE
Waiting for wine to close

### ISSUE THREAD

**Issue by yellow-dev12** [roblox-linux-wrapper/roblox-linux-wrapper#205]
When i launching roblox it says "starting game" and then i have this issue
![image](https://user-images.githubusercontent.com/78827697/136613942-ed9a09c2-f7b9-4041-b3b2-7da6e440be29.png)
My sister gonna kill me xD

**Comment by yellow-dev12** [comment]
yea that's russian text cuz i'm from Russia

**Comment by harshetmaruff** [comment]
the same issue with me 
os: ubuntu 20.04 64 bit
wine version: 6.20

**Comment by harshetmaruff** [comment]
harshet@harshet-desktop:~/Documents/apps/gits/roblox-linux-wrapper$ ./rlw 
> main: Sourcing /home/harshet/Documents/apps/gits/roblox-linux-wrapper/data/rlw-core.sh
> wineinitialize: sourcing /home/harshet/.rlw/wine_choice
> wineinitialize: source complete
> wineinitialize: wine path set to /usr/bin/wine
> wineinitialize: wineserver path set to /usr/bin/wineserver
> wineinitialize: Wine version wine-6.20 is installed
Roblox Linux Wrapper 2017.06.21-15-ge6c2507

**Comment by alfonsojon** [comment]
I'm going to look into this

**Comment by theyseemebowlin** [comment]
This is the same issue for me too, I am running the latest version of wine, 7.1, with Ubuntu 20.04, 64 bit.

**Comment by theyseemebowlin** [comment]
I think I am facing the same issue as #203

**Comment by theyseemebowlin** [comment]
Any updates?

**Comment by theyseemebowlin** [comment]
Hello?

**Comment by alfonsojon** [comment]
I have not fixed this yet

**Comment by theyseemebowlin** [comment]
okay, thanks for telling me

**Comment by alfonsojon** [comment]
This should be resolved with today's release
