### ISSUE TITLE
How to open installed game?

### ISSUE THREAD

**Issue by kangarooo** [roblox-linux-wrapper/roblox-linux-wrapper#207]
So i have menu to install, choose wine version, uninstall, but not to play after i have installed it.
How to start then is not written in instructions. What command? Where is it installed?

**Comment by alfonsojon** [comment]
At that point you can visit roblox.com in your browser and play

**Comment by kangarooo** [comment]
Ok, so i got in debian installed commands from install and it opens when launching some game from .com but  i loads, shows game roblox loading and roblox game selected game loading picture and got error

![roblox error (copy)](https://user-images.githubusercontent.com/73187/148857614-cf06925c-0a00-40ee-bfe5-3c87aafa687b.png)
