### ISSUE TITLE
When i launch roblox linux wrapper it says invalid desktop entry file /home/pi/desktop/roblox-linux-master/-roblox.desktop

### ISSUE THREAD

**Issue by baldbuffalo** [roblox-linux-wrapper/roblox-linux-wrapper#209]

**Comment by baldbuffalo** [comment]
Can someone please help me

**Comment by alfonsojon** [comment]
So, this is probably not the cause of your issue but this will not work on a Raspberry Pi.

If you are running this on a regular PC, try deleting and reinstalling
