### ISSUE TITLE
An Unexpected Error Occured And Roblox Need To Quit(on EndeavourOS)

### ISSUE THREAD

**Issue by ItzburmaSucksAtSoftware** [roblox-linux-wrapper/roblox-linux-wrapper#214]
I distro hopped to EndeavourOS and tried to install roblox and i got the same errors (mostly) everyone got

**Comment by Yosh1002** [comment]
grapejuice

**Comment by alfonsojon** [comment]
@ItzburmaSucksAtSoftware Can you provide the following info:
- Graphics card
- Version of wine
- Any modifications to the script you may have made
- Any settings you've changed

**Comment by farvardin** [comment]
I had the same error. 

I was using the default wine on Linux Mint 20 (ubuntu 20.04), which was version 5.0. I've upgraded to winehq-devel (winehq-stable should do the job as well), which is wine 7.18, and now everything is working fine!
