### ISSUE TITLE
Roblox studio not work lol

### ISSUE THREAD

**Issue by Rebrox090** [roblox-linux-wrapper/roblox-linux-wrapper#215]
Hello. when i start RbxStudio a error appear "route not found" and later "there is no windows program configured to open this type of file".
im using a Linux,Ubuntu 20.04 and wine 7.0 anyone can help me? :(

**Comment by Yosh1002** [comment]
grapejuice

**Comment by alfonsojon** [comment]
Can you provide screenshots of the issue?

**Comment by Rebrox090** [comment]
Hello.Chill i view what Roblox Studio not works more for Pc´s with DirectX11 and my Pc have it. Bruh
