### ISSUE TITLE
Can you provide screenshots of the issue?

### ISSUE THREAD

**Issue by Rebrox090** [roblox-linux-wrapper/roblox-linux-wrapper#217]
Can you provide screenshots of the issue?

_Originally posted by @alfonsojon in https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/issues/215#issuecomment-1237509264_

Hello.Chill i view what Roblox Studio not works more for Pc´s with DirectX11 and my Pc have it. Bruh

**Comment by alfonsojon** [comment]
Please post the screenshots in the existing issue #215
