### ISSUE TITLE
To create a snap package?

### ISSUE THREAD

**Issue by heidiwenger** [roblox-linux-wrapper/roblox-linux-wrapper#218]
For an easy installation, clicking "Install" at Snap Store in Ubuntu, which is the first Linux distro for many new users now coming to Linux. Solus, KDE Neon, Manjaro, MakuluLinux, Ubuntu MATE etc. support snapd by default too.

As i read here, many seemed to end up in the world of pain trying to install Roblox Linux Wrapper. Maybe it is time to attempt a creation of a simple package with all dependencies and in secure sandbox? I mean, why not aim for a simple user friendly way to install on Linux? A snap package also enables an easy roll back or a version in case of need. 

The required dependencies git, wget, latest wine, and zenity would all be there in snap package included without a hassle nor terminal. Normal users will not open the terminal. They hate it as far as i know. They want click and install, run.

Every single part of Snap that you come into contact with is open source. The package format, the daemon, the website (snapcraft.io), and the Snap Store that runs on your system. 

The only part that is not is some piece of the backend on Ubuntu's servers.

Could a snap package by any chance be possible then? A simple one click install, that is. Thanks.

**Comment by heidiwenger** [comment]
> Just use GrapeJuice.

There is a flatpak https://flathub.org/apps/details/net.brinkervii.grapejuice but for example on Ubuntu flatpak support is not installed by default and takes lots of effort for a new user (most will never even start the process, thinking Linux is too hard still). 

As a snap package this wrapper or with the Grapejuice help it, could be installed easily by clicking Install on the Ubuntu Software.

A snap package would help all users, too.

**Comment by alfonsojon** [comment]
A snap package would be nice and an easy way to distribute this. We could also go with Flatpak since more systems support it - not sure.

It's not a high priority at all but I definitely think it sounds neat.

**Comment by alfonsojon** [comment]
> Just use GrapeJuice.

This is not helpful commentary, while Grapejuice is neat I feel the scope of these two projects are pretty different.

**Comment by heidiwenger** [comment]
I have now put a heads up also on the Snapcrafters midst at the snap request forum https://forum.snapcraft.io/t/roblox-linux-wrapper-the-developer-up-for-a-snap-package/32182

They can assist you on this work, i'm sure, if you need help.

**Comment by alfonsojon** [comment]
Thanks!
