### ISSUE TITLE
Someone please confirm if voice chat works in it?

### ISSUE THREAD

**Issue by i6c** [roblox-linux-wrapper/roblox-linux-wrapper#219]
Please let me know if I can voice chat with Roblox Linux wrapper - disregarding all of the BS with default input device

**Comment by i6c** [comment]
Honestly, I don't know how to pass through a mic into wine but has anyone tried this? I need help, I haven't use my computer in months i am pretty rusty.

**Comment by TheComputerGuy96** [comment]
@i6c It seems to work for me 🐸

**Comment by i6c** [comment]
> @i6c It seems to work for me 🐸

OK,  I wanted to confirm before installation ,  thanks
