### ISSUE TITLE
Error while trying to join game

### ISSUE THREAD

**Issue by ThePedroo** [roblox-linux-wrapper/roblox-linux-wrapper#220]
I am currently trying to join a game, but everytime I get this error:
![image](https://user-images.githubusercontent.com/73797168/202081252-94c32e01-45f5-42b7-a12d-8dcd6ddd267c.png)

I'm using wine 6.0.4, the one installed with `pkg install wine` and the latest version of `roblox linux wrapper`.

Machine: FreeBSD 13.1-RELEASE x64 with integrated graphics (GNOME)

Edit: "Show details" button doesn't show any detail, just says to wait that will show the details but it never does.

**Comment by goldstar611** [comment]
Roblox works great on wine-staging. I'm on version 8.0-rc2. I try to keep on staging so when something breaks I can open an issue at winehq.
