### ISSUE TITLE
Roblox new anticheat

### ISSUE THREAD

**Issue by Coder2195Text** [roblox-linux-wrapper/roblox-linux-wrapper#222]
For those who don't know roblox anticheat blocks wine now.

More info at this issue

https://github.com/vinegarhq/vinegar/issues/59

**Comment by ntvmb** [comment]
Wine is no longer blocked. Please close this issue.

**Comment by Coder2195Text** [comment]
> Roblox no longer blocks Wine. Please close this issue.

thanks I forgot to do it

**Comment by ntvmb** [comment]
I would also like to remind everyone to use the upstream version of RLW (just clone the repository) since the current release (2022.09.05 as of writing this) creates 32-bit Wine prefixes which is no longer supported by Roblox. The upstream version does create a 64-bit Wine prefix.
