### ISSUE TITLE
Roblox thinks Im 32 bit

### ISSUE THREAD

**Issue by DatDerpyDude81** [roblox-linux-wrapper/roblox-linux-wrapper#223]
Roblox couldn't install because it said I can't use 32 bit, however I am 64 bit.

**Comment by TheComputerGuy96** [comment]
@DatDerpyDude81 What is the exact error? 🐸

**Comment by Lavadude82** [comment]
![image](https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/assets/98785801/e6558ce6-8b9a-4d83-8bd8-1e422bbfbdab)

**Comment by Lavadude82** [comment]
after runnign ./rlw and selecting $PATH option, it created a new one since there wasnt one, then it started to install roblox but then this error happened.

**Comment by gabrielnn77** [comment]
same issue here, fedora 38 - wine 8.13

**Comment by TheComputerGuy96** [comment]
> same issue here, fedora 38 - wine 8.13

@gabrielnn77 RLW now explicitly creates 64-bit prefixes (I think you need to recreate your prefix if it's still 32-bit though)

**Comment by ntvmb** [comment]
> > same issue here, fedora 38 - wine 8.13
> 
> @gabrielnn77 RLW now explicitly creates 64-bit prefixes (I think you need to recreate your prefix if it's still 32-bit though)

You have to use the upstream version. The current release does not create 64-bit prefixes, only 32-bit.

**Comment by ntvmb** [comment]
> Roblox couldn't install because it said I can't use 32 bit, however I am 64 bit.

@DatDerpyDude81 The current release still creates a 32-bit prefix. I have remedied this issue upstream (see #221 for more info) so use that version. (simply clone the repository; you don't need to compile anything)

**Comment by ntvmb** [comment]
Please close this issue as it has already been fixed upstream.

**Comment by DatDerpyDude81** [comment]
Closing
