### ISSUE TITLE
installing not working

### ISSUE THREAD

**Issue by sleepy124** [roblox-linux-wrapper/roblox-linux-wrapper#224]
hey, so when i have installed all the required repositories/ goit, wget, wine, zenity and all that when iopen the rlw file it shows this https://imgur.com/a/Y81n9rA

**Comment by ntvmb** [comment]
1. Open a terminal in the directory where RLW is located
2. Type `./rlw` to run RLW

If it gives you a `Permission denied` error make sure it's marked as executable: `chmod +x ./rlw`
