### ISSUE TITLE
Roblox no longer supports Windows 32 bit devices.

### ISSUE THREAD

**Issue by unheck** [roblox-linux-wrapper/roblox-linux-wrapper#226]
![image](https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/assets/145664642/5c61f297-75e2-47ac-bf40-be3993b185dd)
How do I get it to run in 64 bit?

**Comment by alfonsojon** [comment]
Using the latest Roblox Linux Wrapper, open `rlw.sh` and reinstall Roblox. This should generate a new Wine prefix that is 64 bit and allow you to play, to the limited degree that is currently supported.
