### ISSUE TITLE
Test Solo not fully loading

### ISSUE THREAD

**Issue by ghost** [roblox-linux-wrapper/roblox-linux-wrapper#78]
It freezes execution half way. [Picture](https://twitter.com/ItsEprent/status/588757251512401920)

**Specs:**
* Intel HD Graphics (onboard)
* Ubuntu 14.04
* Latest Wine version

After further research, it only happens when a script is using memory at the time. No idea why.

**Comment by eprent** [comment]
Sorry! Apparently all of ROBLOX is having an issue with GUI replication causing ROBLOX, not a RLW bug.

**Comment by GLolol** [comment]
> After further research, it only happens when a script is using memory at the time. No idea why.

Can you elaborate? Is this reproducible with the latest version of RLW in master?

**Comment by eprent** [comment]
Yes it's the latest version, when I have scripts or GUI somewhere in the game, Studio will only load half way. Otherwise (let's say it's only a map) it loads flawlessly.

**Comment by NokiaGuy** [comment]
@GLolol It now works under a better (1080p) display, rather than a 720p display.

Very odd, however this display is temporary.

**Comment by GLolol** [comment]
Can you reproduce with the latest Wine and RLW? Also, the picture link doesn't work anymore.

**Comment by StripedFelines** [comment]
This is my previous (deleted) account, can't reproduce it anymore.

**Comment by GLolol** [comment]
(You can rename your account on GitHub in case you didn't know...)

Closing then.

**Comment by StripedFelines** [comment]
I didn't realize it at the time lol.
